### ISSUE TITLE
Packaged App Size

### ISSUE THREAD

**Issue by timfish** [jimschubert/electron-aurelia-example#1]
Many thanks for putting this together, its been very useful!

I've been playing around with Electron and Aurelia, attempting to get a good directory structure to make packaging simpler and reducing the unnecessary files. Your structure is the best I've found so far.

I'm still trying to work out how I can keep the packaged size sensible.

Are most of the hard dependencies in `package.json` simply so that the tests can be run in the app? Currently `node_modules` compresses down to about 10MB before I've even started the app!

With `jQuery` and `materialize` included, my `jspm_packages` is now bloated to over 25MB compressed so I think I'll need to consider bundling and excluding `jspm_packages` when packaging the app.

Any thoughts?

**Comment by jimschubert** [comment]
I think bundling should work. I'm working on e2e testing, which will most likely remove the need to run tests from within the app.

I've gotten e2e tests working, but they're inconsistent. Sometimes they fail on a script timeout before even starting through webdriverio. I had spent three days trying through protractor and the app couldn't seem to read the files. There's a weird problem where `require('./something')` in client code doesn't resolve correctly when running through end to end tests and I had to hack a solution to get tests to pass.

I can clean up my local branch and push that to github if you want to take a look.

I haven't checked out materialize or jquery, but I'd check to see if you're pulling down more than client code. I'm new to jspm, but I've seen that you can limit the files in dependencies through config.

**Comment by timfish** [comment]
I'm attempting to learn JavaScript development in its entirety through others examples!

[This recent blog post](http://blog.durandal.io/2015/06/09/aurelia-early-june-release/) does detail the upcoming CLI which should help bundling and we can then exclude most of the `jspm_packages` directory:

> CLI - In the next week you will see a new release of our CLI along with an accompanying blog post detailing how you can bundle both your JS and HTML for application deploy. 

The materialize repo is quite large and I don't think the whole lot was intended for production distribution. 

Its probably best if I concentrate on the app development for now and the tooling and packaging will catch up. Its easy to forget that Aurelia hasn't even made it to beta!

**Comment by jimschubert** [comment]
@timfish did you have a chance to try that change? If that fixes the problem, we can close this.  The electron framework is still pretty hefty, though.

**Comment by timfish** [comment]
Yes, thanks for that, I did remove quite a chunk so this can be closed! 

I've been reading [this blog post](http://blog.durandal.io/2015/06/23/bundling-an-aurelia-application/) from earlier in the week which details some of the new resources bundling. It looks like `aurelia-cli bundle` command wraps `jspm bundle` which might mean we can exclude everything in  `jspm_packages` apart from `system.js`. I've not had a chance to test it but that could save another 25MB compressed.

**Comment by jimschubert** [comment]
Awesome. Thanks for the link!
